# fly.toml app configuration file generated for twitterfix on 2023-11-15T17:27:46-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "twitterfix"
primary_region = "yyz"

[build]
